fix fc "NoClassDefFoundError"
MIUI-24101

Change-Id: Ia2b77054a8a9f346a11b20d8ba08a47d5939c3c7

Conflicts:

	framework.jar.out/smali/com/android/internal/telephony/gsm/SmsMessage.smali